#!/usr/bin/env python

import os, sys, time, random, socket

def usage():
    print "Usage: %s PORT FILE"
    print "\tPORT is the TCP port to bind to"
    print "\tFILE is the file to read - one packet per line"


if len(sys.argv) < 3:
    usage()
    exit(-1)

PORT = int(sys.argv[1])
FILE = sys.argv[2]
clients = []

s = socket.socket(
    socket.AF_INET, socket.SOCK_STREAM)

s.bind((socket.gethostname(), PORT))
s.listen(5)

(client, address) = s.accept()

f = open(FILE)
while 1:
    for l in f:
        client.send(l)
        time.sleep(random.randint(1, 10))
    
